- name: This playbook will provision two ubuntu ansible node containers
  hosts: localhost
  tasks:
  - name: Install Docker SDK for ansible to communicate  with docker server
    shell: pip install docker

  - name: Provision ubuntu ansible node
    docker_container:
       docker_host: "tcp://localhost:4243"
       image: "tektutor/ubuntu-ansible-node:latest"
       name: "ubuntu-{{item}}"
       hostname: "ubuntu-{{item}}"
       state: started 
       published_ports:
       - "2{{item}}:22"
       - "8{{item}}:80"
    with_sequence: count=2 format="%03d" 
         

