- name: This playbook will build jenkins slave node image
  hosts: localhost
  tasks:
  - name: Cleanup all jenkins slave containers
    shell: docker rm -f $(docker ps -aq --filter="name=docker-slave*")
    ignore_errors: yes

  - name: Install Docker SDK for ansible to communicate  with docker server
    shell: pip install docker

  - name: Remove the existing Jenkins slave image
    docker_image:
      name: tektutor/jenkins-slave-node:latest
      state: absent

  - name: Build Jenkins slave node image
    docker_image:
      name: tektutor/jenkins-slave-node:latest
      build:
        path: .
        pull: no
      state: present
      source: build 


