FROM ubuntu:18.04 
MAINTAINER Jeganathan Swaminathan <jegan@tektutor.org>

RUN apt update && apt install -y software-properties-common && add-apt-repository ppa:openjdk-r/ppa && apt update && apt install -y openjdk-17-jdk maven git 
