#!/usr/bin/env groovy
pipeline {
    agent {
        label 'docker-slave'
    }
    stages {
        stage('Build Jenkins Slave Node Container Name') {
           agent {
              label 'built-in'
           }
	   steps {
              script {
                 dir("Day5/devops-pipeline") {
                    sh "ansible-playbook -i inventory build-docker-image-playbook.yml"
                 }
              }
           }
        }
        stage('Compile') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean compile"
		    }
                }
            }
        }
        stage('Unit Test') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn test"
		    }
                }
            }
        }
        stage('package') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn package"
		    }
                }
            }
        }
        stage('Install') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn install"
		    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn deploy"
		    }
                }
            }
        }
        stage('Static Code Analyis - SonarQube') {
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean verify sonar:sonar \
                               -Dsonar.projectKey=tektutor \
                               -Dsonar.host.url=http://192.168.167.139:9000 \
                               -Dsonar.login=sqp_df4cfe42450f0fbf402241f256d5de42fd17b115"
		    }
                }
            }
        }
    }
}
