#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
#        stage('Build Jenkins Slave Node Container Name') {
#           agent {
#              label 'built-in'
#           }
#	   steps {
#              script {
#                 dir("Day5/devops-pipeline") {
#                    sh "ansible-playbook -i inventory build-docker-image-playbook.yml"
#                 }
#              }
#           }
#        }
        stage('Compile') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean compile"
		    }
                }
            }
        }
        stage('Unit Test') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn test"
		    }
                }
            }
        }
        stage('package') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn package"
		    }
                }
            }
        }
        stage('Install') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn install"
		    }
                }
            }
        }
        stage('Deploy') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn deploy"
		    }
                }
            }
        }
        stage('Static Code Analyis - SonarQube') {
   	    agent {
        	label 'docker-slave'
	    }
            steps {
                script {
                    dir("Day2/multi-module-project") {
                    	sh "mvn clean verify sonar:sonar \
                               -Dsonar.projectKey=tektutor \
                               -Dsonar.host.url=http://192.168.167.139:9000 \
                               -Dsonar.login=sqp_df4cfe42450f0fbf402241f256d5de42fd17b115"
		    }
                }
            }
        }
    }
}
